# This workflow will build a Java project with Maven and run Unit Test 

#workflow display name

name: Java CI with Maven

#TRIGGERS SECTION
on:
  #trigger current WF on push event on main branch
  push:
    branches: [ "main" ]
  #trigger current WF on Pull Request event on main branch
  pull_request:
    branches: [ "main" ]

#JOBS SECTION
jobs:
  build:
    #job display name
    name: Build & Test

    #run workflow on ubuntu latest version container 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repo
      #checks-out repo under $GITHUB_WORKSPACE, so workflow can access it
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      #sets up a JDK CLI environment for use
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        
    - name: Build and Test with Maven
      #run Maven build and JUnit Test 
      run: mvn test 
